title: Nishita Kapoor # your name (or website title) here
logo: "/images/my_picture_2.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Armed with a biotechnology background, I worked extensively on diverse research projects around the world. 
  During the pandemic, I realized the true potential of AI and data science in addressing some of the most important challenges in healthcare, such as 
  medical diagnostics, prognosis, treatement etc.
  Passionate to play my part in this revolution, I am excited to step into the field of AI for healthcare and help transform people's lives.
  <br><br>
  I am actively seeking opportunities where I can leverage AI and data science to solve healthcare challenges and result in translational advancements.
  <br><br>
  <a href="https://www.linkedin.com/in/nishitakapoor/">View My LinkedIn Profile</a>
  <br><br>
  <a href="">View My Resume</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
