title: Nishita Kapoor # your name (or website title) here
logo: "/images/my_picture_2.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I developed my interest in data science during the Covid pandemic. I was fascinated by the insights we can get from the data and applications of AI to biomedical
  industry such as in diagnostics etc. I have a Master's in Biotechnology and extensive biomedical research experience. Being passionate about the healthcare industry,
  I was excited about gaining these new skills and started on this new path towards data science. 
  Since pursuing this goal of Data Science I have learned that I love problem solving. 
  <br><br>
  I am now seeking opportunities where I can leverage AI and data science to solve problems in the biotechnology/healthcare industry and result in translational advancements.
  <br><br>
  <a href="https://www.linkedin.com/in/nishitakapoor/">View My LinkedIn Profile</a>
  <br><br>
  <a href="">View My Resume</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
