title: Nishita Kapoor # your name (or website title) here
logo: "/images/my_picture_2.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  .
  .
  .
  .
  .
  
  <br><br>
  I am interested in opportunities at the intersection of Data Science and Biology that result in technological advancements.
  <br><br>
  <a href="https://www.linkedin.com/in/nishitakapoor/">View My LinkedIn Profile</a>
  <br><br>
  <a href="">View My Resume</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
